# Generated by Django 4.1.3 on 2022-12-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='size',
            field=models.CharField(default='XL', max_length=5),
            preserve_default=False,
        ),
    ]
